version: '3'

services:
  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./pagebina:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/etc/nginx/conf.d
      - /etc/letsencrypt/live/binariosolucoes.com.br/fullchain.pem:/etc/nginx/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/binariosolucoes.com.br/privkey.pem:/etc/nginx/ssl/private/privkey.pem
