version: '3'

services:
  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./pagebina:/usr/share/nginx/html
    # Adicione volumes adicionais conforme necessário para configurar Nginx ou outros serviços

  # Adicione outros serviços conforme necessário
