version: '3'

services:
  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./pagebina:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Certifique-se de que o caminho está correto
      - /etc/letsencrypt/live/binariosolucoes.com.br/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/binariosolucoes.com.br/privkey.pem:/etc/ssl/private/privkey.pem:ro
    # Adicione volumes adicionais conforme necessário para configurar o Nginx ou outros serviços
