# Use a imagem Nginx
FROM nginx

# Copie os arquivos do projeto para o diretório padrão do Nginx
COPY ./ /usr/share/nginx/html/

# Copie o arquivo de configuração do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponha a porta 80 (a porta padrão do Nginx)
EXPOSE 80
