version: '3'

services:
  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./pagebina:/usr/share/nginx/html
      - /etc/letsencrypt/live/binariosolucoes.com.br/fullchain.pem:/etc/nginx/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/binariosolucoes.com.br/privkey.pem:/etc/nginx/ssl/private/privkey.pem:ro
    # Adicione volumes adicionais conforme necessário para configurar o Nginx ou outros serviços

    # Configurações adicionais para o Nginx
    environment:
      - NGINX_SERVER_NAME=binariosolucoes.com.br www.binariosolucoes.com.br
      - NGINX_SSL_CERTIFICATE=/etc/nginx/ssl/certs/fullchain.pem
      - NGINX_SSL_CERTIFICATE_KEY=/etc/nginx/ssl/private/privkey.pem
      - NGINX_SSL_PROTOCOLS=TLSv1.2 TLSv1.3
      - NGINX_SSL_CIPHERS=TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
